name: NoteTaker
options:
  bundleIdPrefix: com.incept5
  deploymentTarget:
    macOS: "14.2"
  xcodeVersion: "15.0"
  minimumXcodeGenVersion: "2.35"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.2"

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.15.0"
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: "7.0.0"
  MLXSwiftLM:
    url: https://github.com/ml-explore/mlx-swift-lm.git
    from: "2.0.0"

schemes:
  NoteTaker:
    build:
      targets:
        NoteTaker: all
    run:
      config: Debug
    archive:
      config: Release

targets:
  NoteTaker:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Resources
      - Assets.xcassets
    dependencies:
      - package: WhisperKit
      - package: GRDB
      - package: MLXSwiftLM
        product: MLXLLM
      - framework: EventKit.framework
        embed: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.incept5.NoteTaker
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/NoteTaker.entitlements
        GENERATE_INFOPLIST_FILE: false
        ENABLE_HARDENED_RUNTIME: true
